config/routes.rb
Rails.application.routes.draw do
  root "static_page#welcome"
  resources :workouts
  resources :users do 
    resources :routines
  end

  get '/login', to: 'sessions#new'
  #get '/auth/google/callback', to: 'users#google_login'
  post '/login', to: 'sessions#create'
  delete '/session', to: 'sessions#destroy'
  get '/auth/facebook/callback' => 'sessions#fb_create'
  get '/search' => 'workouts#search', :as => 'search_workout'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/routine.rb
class Routine < ApplicationRecord
    belongs_to :user
    belongs_to :workout
    def workout_name=(workout)
        self.workout = Workout.find_or_create_by(name: workout)
    end
    
    def workout_name
        self.workout.name if self.workout
    end

    def workout_cals=(workout)
        self.workout = Workout.find_or_create_by(name: workout)
    end
    
    def workout_cals
        self.workout.calories_burned if self.workout
    end
    
    
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    has_many :routines
    has_many :workouts, through: :routines

    #validations
    validates :name, presence: true
    validates :email, presence: true, uniqueness: true
    
end

app/models/workout.rb
class Workout < ApplicationRecord
    has_many :routines
    has_many :users, through: :routines

    #validations
    validates :muscle_group, presence: true
    validates :name, presence: true, uniqueness: true

    scope :search, -> (query) { where("muscle_group LIKE ?", "%" + query + "%") }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :current_user, :require_login, :authorize_resource

    def current_user
      if session[:user_id].present?
        user = User.find_by(:id => session[:user_id])
      end
    end

    def authorize_resource(resource)
      if resource.user != current_user
        flash[:danger] = "Nice try, but you don't have permission to perform this action"
        redirect_to root_url
      end
    end
  
    def require_login
      unless current_user
        redirect_to root_url
      end
    end

    def logged_in?
        !!session[:id]
    end
    
    def authenticate 
        if !logged_in?
          redirect '/login'
        end
    end

    
end

app/controllers/routines_controller.rb
class RoutinesController < ApplicationController
  before_action :require_login

    def index
        if params[:user_id]
            @user = User.find(params[:user_id])
            @routines = current_user.routines
        else
            redirect_to root_url
        end
    end

    def new
        @user = User.find(params[:user_id])
        @routine = @user.routines.new
        
    end

    def create
        @user = User.find(params[:user_id])
        @routine = @user.routines.new(routine_params)
        @routine.user = User.find_by(id: params[:user_id])
        if @routine.save
            flash[:success] = "Workout was successfully added to your list"
            redirect_to user_routines_path(@user)
        else
          flash[:danger] = "This Routine Could not be Created :("
          render :new 
        end
    end

    def show
        @routine = current_user.routines.find(params[:id])
        workouts = current_user.workouts
        workouts.each do |workout|
            if @routine.workout_id == workout.id
                @works = workout
            end
        end
        @works
    end

    def edit
      @routine = current_user.routines.find(params[:id])
      authorize_resource(@routine)  
      @user = User.find(params[:user_id])

    end
  
    def update
        @user = User.find(params[:user_id])
        @routine = Routine.find(params[:id])
        @routine.update(routine_params)
 
      if @routine.save
        flash[:success] = "#{@routine.title} updated!"
        redirect_to user_routine_path(current_user, @routine)
      else
        flash[:danger] = "#{@routine.title} wasn't able to be updated. Please try again!"
        render :edit
      end
    end
  
    def destroy
        @routine = current_user.routines.find(params[:id])
        if @routine
          @routine.destroy
          flash[:success] = "Your routine has been deleted"
          redirect_to user_routines_path(current_user)
        else
          flash[:danger] = "This routine could not be deleted"
          redirect_to user_routine_path(current_user, @routine)
        end
    end

      private

  def routine_params
    params.require(:routine).permit(:title, :date, :workout_id, :workout_name, :reps, :workout_cals)
  end

  

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new
        
    end
    
    def create
        user = User.find_by(email: params[:session][:email].downcase)
        if user && user.authenticate(params[:session][:password])
            session[:user_id] = user.id
            redirect_to user_path(user)
        else
            flash[:danger] = "Wrong email and/or password"
            render :new
        end
    end

    def fb_create
        @user = User.find_or_create_by(email: auth[:info][:email]) do |u|
            u.name = auth['info']['name']
            u.email = auth['info']['email']
            u.password = SecureRandom.urlsafe_base64

        end
        session[:user_id] = @user.id
        redirect_to user_path(@user)
    end

    def destroy
        if current_user
            session.delete :user_id
            redirect_to root_url
        end
    end
    private
 
    def auth
      request.env['omniauth.auth']
    end
    
end

app/controllers/static_page_controller.rb
class StaticPageController < ApplicationController
    def welcome

    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :require_login, except: [:new, :create]
    def new
       @user = User.new
    end

    def create
        @user = User.create(user_params)
        if @user.save
            session[:user_id] = user.id
            redirect_to user_path(user)
        else
          flash[:dange] = "Something went wrong, please try again. Make sure you enter your name, email and password"  
          redirect_to new_user_path
        end
    end

    def show
        @user = User.find(params[:id])
    end

    def edit 
        @user = User.find(params[:id])
    end

    def update
        @user = User.find(params[:id])
        @user.update(user_params)
        if @user.save
          flash[:success] = "Your information has been updated"
          redirect_to user_path(@user)
        else
          flash[:danger] = "Your info couldn't get updated"
          redirect_to user_edit_path 
        end
      end

      def google_login
        @user = User.find_by(email: auth[:info][:email])
    
        if @user.nil?
          @user = User.new(
            email: auth[:info][:email],
            username: auth[:info][:name],
            password: SecureRandom.urlsafe_base64
          )
        end
    
        if @user.save
          session[:user_id] = @user.id
          redirect_to user_path(@user)
        else
          render :new
        end
      end

    
    private
    def user_params
        params.require(:user).permit(:name, :age, :email, :password, :password_confirmation, :weight, :height)
    end

    def auth
        request.env['omniauth.auth']
    end
end

app/controllers/workouts_controller.rb
class WorkoutsController < ApplicationController
    before_action :require_login
    def index
        @workouts = Workout.all
    end

    def show
        @workout = Workout.find_by(id: params[:id])
    end
    
    def new
        @workout = Workout.new
     end
 
     def create
         @workout = Workout.create(workout_params)
         if @workout.save
            flash[:success] = "New workout was created!"
            redirect_to workout_path(@workout)
         else
            flash[:danger] = "This workout could not be added"
            redirect_to new_workout_path
         end
     end

     def search
        @workouts = Workout.search(params[:query])
        render :index
     end


    private
    def workout_params
        params.require(:workout).permit(:name, :time, :calories_burned, :muscle_group)
    end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/routines_helper.rb
module RoutinesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/static_page_helper.rb
module StaticPageHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/workouts_helper.rb
module WorkoutsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  <link href="https://fonts.googleapis.com/css?family=Montserrat+Subrayada|Ubuntu&display=swap" rel="stylesheet">
  <title>WorkoutTracker</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag  'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div>
    <% flash.each do |k,v| %>
      <div class="<%= k %>"><p><%= v %></p></div>
    <% end %>
  </div>
  <% if !current_user %>
          <a class="navbar-brand" href="<%= new_user_path %>"/>Sign Up</a>
          <%= link_to "Log in", login_path, class:"navbar-brand" %>
        <% end %>
        <% if current_user %>
          <%= link_to "#{current_user.name}'s profile", user_path(current_user), class:"navbar-brand"%>
          <%= link_to "Log Out", session_url, class:"navbar-brand",method:'delete' %>
        <% end %>
    <%= yield %>
  </body>
</html>

app/views/routines/_form.html.erb
<%= form_for [user, routine] do |f| %>
    <%= f.label :title %><br/>
    <%= f.text_field :title, placeholder: 'Enter A Nickname Workout' %><br />
    <%= f.label :date %><br />
    <%= f.date_select :date %><br />
    <%= f.label :reps %>
    <%= f.number_field :reps %><br />
    <%= f.label :workout %><br />
    <%= f.collection_select :workout_id, Workout.all, :id, :name, :prompt => true%><br/>
    <br/>
    <%= f.submit %>
   
<% end %>

app/views/routines/edit.html.erb
<h1> Edit Your Routine </h1>
<%= render partial: 'form', locals: {user: @user, routine: @routine} %>
<%= link_to "Back", user_routines_path(current_user) %> 

app/views/routines/index.html.erb
<h2>Your Routines:</h2>
<% if @routines.empty? %>
    <p> You have no routines yet! </p>
<% else %>
    <ul>
    <% @routines.each do |routine| %>
        <li><%= link_to routine.workout_name, user_routine_path(current_user, routine) %></li>
    <% end %>
    </ul>
<% end %>
<div class="navbar">
<%= link_to "Start New Routine", new_user_routine_path(current_user), class:"navbar-brand" %> 
<%= link_to "See All Available Workouts", workouts_path %> 
<%= link_to "Add New Workout", new_workout_path %> 

</div>

app/views/routines/new.html.erb
<h1> Create Your Routine </h1>
<%= render partial: 'form', locals: {user: @user, routine: @routine} %>
<%= link_to "Back", user_routines_path(current_user) %> 

app/views/routines/show.html.erb
<h2><%= @routine.title %> </h2>
<p> Date Created: <%= @routine.date %> </p>
<p> Number of Reps/Minutes: <%= @routine.reps %> </p>
<h3>Workout:</h3>
<%= @works.name %><br/>
<%= @works.calories_burned %> cal/hr

</br>
</br>
<%= form_tag(user_routine_path(current_user, @routine), method: "delete") do %>
    <%= submit_tag("Delete Routine", class: "btn btn-danger btn-block") %>
<% end %>

<div class="navbar">
<%= link_to "Edit this Routine", edit_user_routine_path(current_user, @routine) %> 
<%= link_to "Back", user_routines_path %> 


</div>

app/views/static_page/welcome.html.erb
<div>
<div style='width: 600px;margin:auto'>
  <img  style='width: 600px' src="https://i.ytimg.com/vi/7RySr4tGrec/maxresdefault.jpg">
</div>
<h1 class="logo"><center>Welcome to Feel The Burn</h1></center>
<h3 align="center">Workout Tracker</h3>
</div>

app/views/users/_form.html.erb
<%= form_for user do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %><br />
    <%= f.label :age %>
    <%= f.number_field :age %><br />
    <%= f.label :email %>
    <%= f.text_field :email %><br />
    <%= f.label :weight %>
    <%= f.number_field :weight %><br />
    <%= f.label :height %>
    <%= f.text_field :height %><br />
    <%= f.label :password %>
    <%= f.password_field :password %><br />
    <%= f.submit %>
<% end %>

app/views/users/edit.html.erb
<h1>Edit!</h1>
<%= render partial: 'form', locals: {user: @user} %>
<br>
<%= link_to "Back", user_path(current_user) %> 

app/views/users/new.html.erb
<h1>Sign Up!</h1>
<%= link_to('Log in with Facebook!', '/auth/facebook') %>
<p>or enter in your details below:</p>

<% if @user.errors.any? %>
<div class="alert alert-danger" role="alert">
  <ul>
  <% @user.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
  <% end %>
  </ul>
</div>
<% end %>

<%= render partial: 'form', locals: {user: @user} %>

app/views/users/show.html.erb
<h2 class="logo">Hello, <%=@user.name%></h2>
<h3> Your info: <br/> </h3>
Age: <%=@user.age%> <br/>
Weight: <%=@user.weight %> lbs <br/>
Height: <%=@user.height %> <br/>
<br/>

<div class="navbar">
     <%= link_to "Add a new Workout", new_user_routine_path(current_user) %> 
     <%= link_to "Edit Your Info", edit_user_path %> 
     <%= link_to "See Your Workouts", user_routines_path(@user) %> 
     <%= link_to "See Available Workouts", workouts_path %> 
</div>

app/views/workouts/index.html.erb
<br/>
<%= form_tag(search_workout_path, :method => "get", class: 'navbar-form navbar-left') do %>  
  <%= form_tag("/search", method: "get") do %>
    <%= label_tag :query, "Search by Muscle Group:" %>
    <%= text_field_tag :query, "", class:"form-control" %>
    <%= submit_tag "Search", class: "btn btn-sm btn-secondary" %>
  <% end %> 

<% end %><h1> Workouts: </h1>
<ul>
<% @workouts.each do |workout| %>
  <li><h3> <%= link_to workout.name, workout_path(workout) %> </h3> </li>
<% end %>
</ul>

<div class="navbar">
<%= link_to "Add a Workout to Your List", new_user_routine_path(current_user) %> 
<%= link_to "See Your Workouts", user_routines_path(current_user) %> 
<%= link_to "Add New Workout to the List", new_workout_path %> 

</div>

app/views/workouts/new.html.erb
<br/>
<%= form_for @workout do |f| %>
    <br/><%= f.label :name %>
    <%= f.text_field :name %><br />
    <%= f.label :calories_burned %>
    <%= f.number_field :calories_burned %><br />
    <%= f.label :time %>
    <%= f.number_field :time, :value => 60 %> min/reps<br />
    <%= f.label :muscle_group %>
    <%= f.text_field :muscle_group %><br /><br/>
    <%= f.submit %> 
<% end %>
<br/>
<%= link_to "Back", workouts_path %> 

app/views/workouts/show.html.erb
<h1> <%= @workout.name %> </h1>
<ul>
<li> Muscle Group: <%= @workout.muscle_group %> </li>
<li> Calories/Hr: <%= @workout.calories_burned %> </li>
</ul>
<br/>
<%= link_to "Add to my Routine", new_user_routine_path(current_user), class:"navbar-brand" %> <br/>
<%= link_to "Back", workouts_path %>